### PR TITLE
Use password file location env var instead of plaintext password env var

### PR DESCRIPTION
**Pull request by cammdavie**
I have tested this on the standalone plugin and haven't found any issues.

### CODE REVIEW

**Comment by cammdavie** [comment]
Isaak had the thought that it would make sense to specify the password file location inside of `config.yaml` instead of going through an environment variable. This does make a lot of sense to me, so if you feel that would be better, I can change the code.

Actually, as I think about it more, if we go the route of using the config file instead of an env var for password file location, it might make the most sense to have a single secrets file whose location is specified in `config.yaml`, with all of the credentials specified in the secrets file.

Thanks,
Cameron

**Comment by cammdavie** [comment]
Hi @runakor ,  I was wondering if you had a chance to consider these possible avenues and if you could tell me your thoughts. Also, Isaak and I were wondering if the current container release is going to be long-term or if there will be updates added in the near future.

Thanks,
Cameron

**Review by runakor — APPROVED** [review]

**Comment by runakor** [comment]
Hi @cammdavie , 

Thanks the change. I merged the PR.
Current docker image will be the long-term image. but it will be updated quickly when new features are added. 

Best,
Sangho Kim

**Comment by cammdavie** [comment]
Thanks @runakor , 

We were also wondering if it was possible to have the container versions tagged so we can work on a static version instead of `latest`?

Thank you,
Cameron

**Comment by runakor** [comment]
Sure. I will apply version tag from next release.

**Comment by cammdavie** [comment]
Thank you!

**Pull request merged**
